export default [
    {
        id: 1,
        img : "/images/Rectangle18.png",
        favorite : '/icons/Heart.png',
        text : 'love',
        type : 'Single',
        duration : '2:56',
        icon : '/icons/Viewchart/more-vertical.png',
        src : '/music/03WetDreamz-Copy.mp3',
    },
    {
        id: 2,
        img : "/images/Rectangle14.png",
        favorite : '/icons/Heart.png',
        text : 'Alarm clock',
        type : 'Burna',
        duration : '3:45',
        icon : '/icons/Viewchart/more-vertical.png',
        src : '/music/1 - Another Level - Copy.mp3',
    },
    {
        id: 3,
        img : "/images/Rectangle16.png",
        favorite : '/icons/Heart.png',
        text : 'Stand strong',
        type : 'Davido',
        duration : '3:55',
        icon : '/icons/Viewchart/more-vertical.png',
        src : '/music/Burna_Boy_Deja_Vu_9jaflaver.com_.mp3',
    },
    {
        id: 4,
        img : "/images/Rectangle20.png",
        favorite : '/icons/Heart.png',
        text : 'comfort',
        type : 'Vector',
        duration : '3:02',
        icon : 'icons/Viewchart/more-vertical.png',
        src : "/music/Drake - God's Plan.mp3",
    },
    {
        id: 5,
        img : "/images/Rectangle28.png",
        favorite : '/icons/Heart.png',
        text : 'Mind Games',
        type : 'Vector',
        duration : '3:03',
        icon : 'icons/Viewchart/more-vertical.png',
        src : '/music/Demmie-Vee-–-Tiff.mp3'
    },
    {
        id: 6,
        img : "/images/Rectangle15.png",
        favorite : '/icons/Heart.png',
        text : 'Mighty wine',
        type : 'wizkid',
        duration : '2:56',
        icon : 'icons/Viewchart/more-vertical.png',
        src : '/music/Cheque-Ft.-Davido-Wale-Zoom-Remix - Copy.mp3'
    }
]